# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 306cca51cfe97ac0e2723c036ec04f710b2786ba507df0027ecd89a98e9a96f374127b2265455c84128c3d713405da68b9a7eeec55bc39f2afb9e719621f1e4e

test:
  secret_key_base: dee6f61a8cf264d5fff9c9930a206d535a04761f2c6d700dc869ab9174846510fc4f30d536dd5606db2987a97ec3319e17a656a9c9dca1760137377a0426802c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
